### ISSUE TITLE
External links shouldn't have duplicate detection...

### ISSUE THREAD

**Issue by furicle** [pmario/file-backups#16]
If you have an external link in TW

e.g. [ext[TWC users|file:///c/users/santa/documents/naughty/]]

Clicking once opens the location in another tab as expected.
Clicking that link a second time (or from a different TW) triggers the duplicate warning.
![image](https://user-images.githubusercontent.com/45774/34052235-87693368-e18f-11e7-9bbe-4ba495d1191f.png)

I don't think that's appropriate when the link is to something external?

**Comment by pmario** [comment]
It doesn't depend on the link. ... 

The plugin compares the browser URL. If it is exactly the same 2 times, imo there should be a warning. If you edit tab 1, then tab2 ... you'll have different version. So saving the stuff to the same xx.html file will cause data loss. 

If you don't have the same URL ... there may be a bug. ...

**Comment by pmario** [comment]
>Clicking once opens the location in another tab as expected.

Can you give an example?

**Comment by furicle** [comment]
Let's say I have a TW with a link to a pdf.

[[file:img/test.pdf]]

First time I click the link, it opens the pdf in a new tab as expected.

Then I go back to the wiki and click the link again....  it opens the pdf in a second tab.  Also as expected.  But it throws up your big red warning box.

That should not happen, unless it's a *TW* that's opened twice.
Opening a pdf, or a jpg, or a website or anything else shouldn't get your box, just TWs.

Is that explained better?     I could make a sample TW I guess, but I'm not sure that would help explain.

**Comment by pmario** [comment]
>Then I go back to the wiki and click the link again.... it opens the pdf in a second tab. Also as expected. But it throws up your big red warning box.

>That should not happen, unless it's a TW that's opened twice.
Opening a pdf, or a jpg, or a website or anything else shouldn't get your box, just TWs.

Ah. OK I'll need to check this. ... deffinitely unwanted behaviour. ... But I'm not sure if there's an easy fix. ...

**Comment by pmario** [comment]
@furicle ... please check out the latest version: https://addons.mozilla.org/en-US/firefox/addon/file-backups/

I did wanted to sign it and distribute it as a beta with github, but it seems I can't have both. listed and self-signed :/

**Comment by furicle** [comment]
Looking good!

Can't duplicate the issue now, using 0.3.5  

(FF 58.02 x64 on Win10)
