### ISSUE TITLE
Save button remains red even if save is succesfull

### ISSUE THREAD

**Issue by morosanuae** [pmario/file-backups#18]
Hi @pmario 

I noticed something strange lately and I think it's something related to the latest version (modifications).
The save button in TiddlyWiki remains red even the file is saved (downloaded) successfully. I'm using Firefox v57.0.2 (64-bit) and TiddlyWiki v5.1.15 (latest).

Thanks and keep up the good work.

**Comment by pmario** [comment]
did you use the latest version. 0.3.4?

**Comment by morosanuae** [comment]
I did now and it seems to be working fine.
Thanks a lot.
