### ISSUE TITLE
Disabled after Firefox restart

### ISSUE THREAD

**Issue by ChristianNext** [pmario/file-backups#19]
Starting a few days ago, file-backups does not work any longer when I restart Firefox. While the "Enable backups" is still ticked on, Firefox offers to save the TiddlyWiki, instead of making a backup.

Workaround: When I disable and enable the AddOn, then all is fine - until the next browser restart.

FF58.0, WIn10, file-backups 0.3.4

**Comment by pmario** [comment]
That's strange. ... 

test 1

 - Can you have a look at the download dropdown. ... 
 - What does it show after a save. ?

test 2

 - restart the browser
 - open a file TW
 - Open the dev console with F12
 - Select the Console tab.
 - Reload a TW with F5. ... 

Does the console say something?

**Comment by ChristianNext** [comment]
test 1 - wants to save as "beakon.tmp.html"
test 2 - no console msg upon reload

But console msg upon (failed) save is:

TiddlyWiki 2.6.4
Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user’s experience. For more help http://xhr.spec.whatwg.org/
inject.js:51:2
XML Parsing Error: not well-formed
Location: file:///C%3A%5CUsers%5CTony%5CDownloads%5CWikis%5CTWNotes.html
Line Number 3198, Column 42:
C%3A%5CUsers%5CTony%5CDownloads%5CWikis%5CTWNotes.html:3198:42
save-wiki error: 
Error: Download canceled by the user

TiddlyWiki 5.1.15
browser-messaging:  file:///C:/Users/Tony/Downloads/Wikis/Releases.html#Draft%20of%20'AddingToBrochures' $:/core/modules/browser-messaging.js:148:3
browser-messaging: Received message from null $:/core/modules/browser-messaging.js:149:3
browser-messaging: Message content 
Object { topic: "mg-loadFrame", data: {…} }
$:/core/modules/browser-messaging.js:150:3
saver-handler: Saving wiki with method autosave through saver tiddlyfox $:/core/modules/utils/logger.js:33:10
browser-messaging:  file:///C:/Users/Tony/Downloads/Wikis/Releases.html#AddingToBrochures $:/core/modules/browser-messaging.js:148:3
browser-messaging: Received message from null $:/core/modules/browser-messaging.js:149:3
browser-messaging: Message content 
Object { topic: "mg-unloadFrame", data: {} }
$:/core/modules/browser-messaging.js:150:3
save-wiki error: 
Error
columnNumber: 1
fileName: "undefined"
lineNumber: 0
message: "Download canceled by the user"
stack: ""
__proto__: Object { … }

**Comment by pmario** [comment]
>test 1 - wants to save as "beakon.tmp.html"

the beakon is needed, to see, where the browser download setting leads to. I did request better feedback from browser API from mozilla. .... But that takes a lot of time, if it es even considered. .... 

>test 2 - no console msg upon reload

ok

**Comment by pmario** [comment]
>TiddlyWiki 2.6.4

Did TWclassic 2.6.4 work with file-backups for you? ... I only tested 2.8.1

**Comment by pmario** [comment]
For TW5. Which plugins do you use?

**Comment by ChristianNext** [comment]
Solved: My FF profile had an issue. All works now on versions TW 5.1.15 and even 2.6.4, after https://support.mozilla.org/en-US/kb/refresh-firefox-reset-add-ons-and-settings 

Thanks Supermario for your help!

**Comment by pmario** [comment]
:)

-m
