### ISSUE TITLE
Save file prompt on autosave in Firefox 59

### ISSUE THREAD

**Issue by alextsui05** [pmario/file-backups#22]
Hi, I enjoy using this addon for saving my Tiddlywiki files conveniently in Dropbox, but recently the file prompt pops up on save as shown in the gif:

![twsave](https://user-images.githubusercontent.com/204991/38217313-e1ededdc-3708-11e8-88bb-c32a4bd9c3ba.gif)

As you can see, it pops up twice: once to save the original file, and again to save a backup file. 
I'm wondering if you had some ideas about what could be going on?

Currently I am running File Backups 0.3.5 on Firefox 59 on Windows 10. The Tiddlywiki file itself is 5.1.13. If there's anything else I can do to help debug, please let me know. Thanks for your work on this project.

**Comment by pmario** [comment]
- Open your browser: Options
 - On General tab scroll down to 
   - Downloads
 - There is an option that says: "Always ask you where to save files" 

If this one is checked, it causes the problem. .. Just disable it and test again.

**Comment by alextsui05** [comment]
@pmario Oh...

You're right, it was as simple as that -- I'm so sorry for that! 💦 (I don't have any memory of changing this setting recently, but I'm glad that's all that was wrong)

Thank you again!
