### ISSUE TITLE
file-backups fails to opt out of "Always ask you where to save files"

### ISSUE THREAD

**Issue by ssokolow** [pmario/file-backups#25]
Something about file-backups is causing it to fire off two or three Save As dialogs on my system for each TiddlyWiki Ctrl+S while other addons like [Web ScrapBook](https://addons.mozilla.org/en-US/firefox/addon/web-scrapbook/) (and my own experiments) get away with streaming a veritable flood of un-prompted files to within my downloads folder without a single prompt.

(On the exact same browser version and profile. When file-backups didn't work as expected, I tried triggering Web ScrapBook to check if something had changed without me noticing.)

**Comment by pmario** [comment]
which plugin version do you use?

**Comment by pmario** [comment]
Please check your browser setting: "Always ask" for downloads. ... If it's checked, it may be a reason to open several "save as" browser popups.

**Comment by pmario** [comment]
Which FF version do you use. .. It seems the FF 63 - beta has an internal problem with lower-case uppercase info loaded from the local store. I'm investigating this problem already.

**Comment by ssokolow** [comment]
I thought I mentioned it but it somehow got lost in the editing. I do have "Always ask" enabled, but file-backups is the only extension which fails to circumvent the Save As dialogs. (ie. I have other extensions which use the same downloads API to save files just fine without opening dialogs)

As for the versions, I'm running file-backups 0.3.5 on a Mozilla build of Firefox Developer Edition 63.0b4 (64-bit) on Kubuntu 14.04.5 LTS. (Kids, don't report bugs while sleep-deprived. You'll forget stuff that's standard to provide.)

**Comment by pmario** [comment]
I'll have a look if I can check or disable the system dialog

**Comment by pmario** [comment]
should be fixed in the next version

**Comment by pmario** [comment]
should be fixed in .10-beta https://github.com/pmario/file-backups/issues/28#issuecomment-525451252
