### ISSUE TITLE
Save Button does not work in Firefox 63

### ISSUE THREAD

**Issue by ywiyogo** [pmario/file-backups#27]
If I activate the plugin, I cannot save my Tiddliwiki at all. Neither the file is updated nor a download window. Disable this plugins, allow me to see the download window.

I use Firefox 63 (64 bit) and Fedora 29.

**Comment by pmario** [comment]
Did you close and restart FF recently?

**Comment by pmario** [comment]
If you manually deactivate/activate the AddOn, you'll need to reload the TW tabs.

**Comment by ywiyogo** [comment]
Yes, I restart the Firefox several times and try to disable and enable with the browser restart afterwards. There is still no response from the browser after clicking the save button.

**Comment by pmario** [comment]
you loaded your TWs from the download dir. right?

**Comment by ywiyogo** [comment]
No, I loaded from another directory.

**Comment by pmario** [comment]
Latest browsers only allow us to save to the browser "Download" directory or a subdirectory in the "Downloads" folder. .. 

If you open a TW from a different folder there should be a "Save As" dialogue pointing to a valid directory. (browser default) .. 

Once the save is done, it should open a green banner, that points you to new file. .. You'll need to use this one.

**Comment by ywiyogo** [comment]
Ok, thanks Mario for the hint that the TW file has to be in the Download folder or its subdirectory. The default browser 'save as' can be used if this addons is disabled.
