### ISSUE TITLE
Consistent "It's not possible to save changes." when I didn't change anything on my end

### ISSUE THREAD

**Issue by ssokolow** [pmario/file-backups#28]
A few weeks ago, I started getting consistent "It's not possible to save changes." messages on my TiddlyWiki Classic wikis. (Yeah, I know. I was lazy and assumed whoever broke it would fix it soon.)

I haven't changed anything, and I have restarted Firefox since then, so I can only assume some changed pushed by either Mozilla or you broke something.

I don't know whether it also affects TiddlyWiki 5 because I just can't muster the willpower to figure out how to port the TiddlyWiki classic theme to it... let alone making enough sense of the internals to port  my prefered extensions to it. (I'd much rather just have someone backport the Ctrl+S fallback saving functionality.)

**Comment by pmario** [comment]
Which version of TWclassic do you use? ... There have been some "saver" changes too. ... So I'm not 100% sure if it is backwards compatible. ...

**Comment by pmario** [comment]
file-backups didn't get any updates lately. ...

**Comment by ssokolow** [comment]
> Which version of TWclassic do you use?

```js
var version = {title: "TiddlyWiki", major: 2, minor: 6, revision: 5, date: new Date("October 6, 2011"), extensions: {}};
```

...and how *is* one supposed to find the version number without looking at the source? I forget.

**Comment by pmario** [comment]
see: https://classic.tiddlywiki.com/#%5B%5Bversion%20macro%5D%5D

**Comment by pmario** [comment]
you are using an older version. ... So it should work. Which OS do you use?

**Comment by pmario** [comment]
> .."It's not possible to save changes."

That's no message from file-backups addOn. ... Is this the exact string that's shown?

**Comment by ssokolow** [comment]
> see: https://classic.tiddlywiki.com/#%5B%5Bversion%20macro%5D%5D

Ahh. I must've removed that from wherever it shows up in the default template. That said, I'm surprised that there's no version information in any of the backstage dropdowns. (eg. "upgrade" would be a good place to tell you what you're currently on.)

> you are using an older version. ... So it should work. Which OS do you use?

Kubuntu Linux 16.04 LTS (temporarily. I'll be upgrading to 18.04 LTS as soon as I've finished fixing things that broke in the move from 14.04 LTS)

> That's no message from file-backups addOn. ... Is this the exact string that's shown?

It's the `cantSaveError` dialog from TiddlyWiki Classic itself.

![Screenshot_20190821_071649](https://user-images.githubusercontent.com/46915/63427663-308df100-c405-11e9-8616-f290ceb50df6.png)

I'm guessing this means that file-backups is failing to hook the save process.

**Comment by pmario** [comment]
>I'm guessing this means that file-backups is failing to hook the save process.

Did you disable the AddOn and then open the wiki-tab?

The addOn only activates the "save hook" at the wiki startup. ....

**Comment by pmario** [comment]
I did test with windows 10. ... I can test with ubuntu 18.04 and FF latest . 

which FF version do you use?
file-backups version?

**Comment by pmario** [comment]
I can reproduce the error message with ubuntu. ... So I can have a closer look.

**Comment by pmario** [comment]
Using TWc latest also has a problem :/ So it won't help to update the wiki :/

**Comment by ssokolow** [comment]
When it first happened, I assumed it might have been the result of a problem I occasionally encounter which I suspect to be caused by either Tree Style Tabs or CanvasBlocker, where I had to kill the WebExtensions process to get the browser to un-freeze.

When that happens, each extension has to be disabled and re-enabled to get it back without restarting the browser, so, yes, I did try disabling and re-enabling the extension, copying my changes to clipboard, reloading the wiki, making my edit again, and then trying to save.

**Comment by pmario** [comment]
hmmm. if file-backups is activated, you have to reload the wiki tab. Otherwise the TW save hook can't be activated.

**Comment by pmario** [comment]
uups. ... you did reload the tab :/ that's strange. .. I'll have a closer look, since I can reproduce the issue on my ubuntu machine. 

There is a difference between windows FF and *nix FF :/

**Comment by webtaster** [comment]
Good afternoon all, and thank you for the software.  Just to say I also get a failure to save, for the last few weeks.  

Linux Mint 18.3
Firefox 68.0.2
Tiddlywiki:  mgsd, based on TW classic 2.5
File-backups 0.3.5, last updated 3rd August 2019.

File-backups was working fine until a few weeks ago, and it still works on Windows 10. 

Cheers,
Jim

**Comment by pmario** [comment]
Hi Jim, 

I did find the problem. It seems for linux system the XHR request for the local file system has been deactivated with latest FF versions. This request still works for windows systems. ... 

TWc version 2.9.2 implemented a "workaround" BUT in combination with file-backups this workaround causes a different problem, because of an oversight on my side. saving with 2.9.2 on *nix systems is also broken. ... I'll try to release a new file-backups  version soon. 

Sorry for the inconvenience. As soon as I do have a working beta, I'll post a link here, so you can test it.

**Comment by webtaster** [comment]
Hi Mario, thanks for the quick reply and for continuing to support this very useful add on.  Looking forward to testing a working beta.  Jim.

**Comment by pmario** [comment]
Sorry for the delay. It's more complicated as it looked like. ... The issue is related with changes in FF 68, that imo uncovered a bug, with path creation, which is part of TW save mechanism for ages. It was ignored by older browsers, but seems to be a "security related" problem now :/

TW 2.6.5 has a different problem than TW 2.9.2 but they are still related to FF 68 changes. 

I think, I can fix both issues with small changes, that will hopefully be future proof.

**Comment by pmario** [comment]
Hi folks, Here's a new BETA please try and give feedback.  

[file_backups-0.3.10-an+fx.xpi.zip](https://github.com/pmario/file-backups/files/3547795/file_backups-0.3.10-an%2Bfx.xpi.zip)

**Comment by webtaster** [comment]
Hi Mario, thanks.  

The BETA is working correctly in my environment:

Linux Mint 18.3
Firefox 68.0.2
Tiddlywiki: mgsd, based on TW classic 2.5
File-backups 0.3.10, last updated 28th August 2019.

All saves are successful, no errors, files created as expected.

Jim

**Comment by pmario** [comment]
no more complains. So it seems to work now.

**Comment by ssokolow** [comment]
Oh, sorry. Something came up and derailed things before I could test it and I wound up completely forgetting. I'll try to test it today or tomorrow and give a final answer on that.

**Comment by webtaster** [comment]
Yes, still working fine on Firefox 69.0.3, setup as above.  Thanks for your efforts pmario.

**Comment by ssokolow** [comment]
Sorry for barely keeping the "today or tomorrow" by even my own skewed day-night cycle.

It seems to work for me too though I've only done minimal testing. Here's what I tested on:

```
Distributor ID: Ubuntu
Description:    Ubuntu 16.04.6 LTS
Release:        16.04
Codename:       xenial
```

```
Name 	Firefox
Version 	69.0.2
Build ID 	20191002192408
```

```
File Backups - For TiddlyWiki	0.3.10	true	file-backups@pmario.github.io
```

```
var version = {title: "TiddlyWiki", major: 2, minor: 6, revision: 5, date: new Date("October 6, 2011"), extensions: {}};
```

**Comment by pmario** [comment]
thx for the feedback

**Comment by webtaster** [comment]
Incidentally, it works on Firefox 70, released a couple of days ago.  Nice.

Linux Mint 18.3
Firefox 70.0
Tiddlywiki: mgsd, based on TW classic 2.5
File-backups 0.3.10.

All saves are successful, no errors, files created as expected.
