### ISSUE TITLE
Fail to work with FF70

### ISSUE THREAD

**Issue by machadcm** [pmario/file-backups#31]
Hi,

When firefox was upgraded to release 70.0 I started to get the following error whenever I started my tiddlywiki page.

"file-backups" has detected another plugin named: "file-backups"
At the moment only 1 save mechanism can be active at once.
We will temporarily deactivate the functionality, until the problem is resolved!

Can you please help?

Thanks,
Miguel

**Comment by machadcm** [comment]
Apparently the problem is already fixed in beta version on https://github.com/pmario/file-backups/releases/tag/V0.3.10-beta.

Thanks!

**Comment by pmario** [comment]
yea, ... I need to make it a release version.

Can you tell, which OS you use?

**Comment by machadcm** [comment]
Win 10 Enterprise 
OS build 16299.1421

Thanks!

**Comment by pmario** [comment]
thx for the feedback!
