### ISSUE TITLE
Doesn't work on new Firefox (v71.0)!

### ISSUE THREAD

**Issue by morosanuae** [pmario/file-backups#33]
Hi,

It doesn't work on the new Firefox (v71.0). I'm getting download failed every time I try to save.
I use Firefox portable (from PortableApps).

Thanks.

**Comment by pmario** [comment]
Hi, Do you have a link for PortableApps FF?

**Comment by pmario** [comment]
Did you try the latest beta? https://github.com/pmario/file-backups/releases/tag/V0.3.10-beta

**Comment by morosanuae** [comment]
Hello,

I've tried the latest beta and has the same problem. The backup functionality is working, the files are downloaded. The simple save is not working (updating the same file). I'm a long time user of Firefox portable (PortableApps) and I didn't have any issues till now.
This is the link to the Firefox portable (PortableApps): [https://portableapps.com/apps/internet/firefox_portable](https://portableapps.com/apps/internet/firefox_portable)

Thanks.

**Comment by pmario** [comment]
I did already find it and did some tests. There is a strange thing going on. 

I did make FF the default browser BUT when I double-click the empty.html it starts FF witout the AddOn. 

So I did: 

 - In File Explorer
 - Right-click empty.html
 - Settings
 - Open with:  FireFox -> Click Change
 - Search the portable app. 

After doing so, double clicking empty.html opens the app with AddOn activated. 

The AddOn is active, if you see the "Blue Diamond" in the "button bar"

**Comment by pmario** [comment]
While experimenting please BACKUP your BACKUPS!!!!!

**Comment by morosanuae** [comment]
> So I did:
In File Explorer
Right-click empty.html
Settings
Open with: FireFox -> Click Change
Search the portable app

Well, this isn't really my normal way of using it. I usually open the browser and I just drag the TiddlyWiki file into a new tab (from the "Downloads" folder of course). The addon is active, I can see the "blue diamond" icon but it doesn't work like usual. Can it be problem introduced in the new version of Firefox?

> While experimenting please BACKUP your BACKUPS!!!!!

I have backups, don't worry.

**Comment by pmario** [comment]
hmmm, As I wrote, it works fine for me. So the main question is: What is different?

Which OS do you use? 

I use Win10 and did my tests within a [Windows Sandbox](https://www.windowscentral.com/how-use-windows-sandbox-windows-10-may-2019-update), to have no side effects. 

You did update FF to Version 71. ... Something else? Any new AddOns, that haven't been used before?

I use "Simple Tab Groups", "uBlock Origin", "Notes by Firefox" and "Feedbro". I'm pretty sure they work well with "file-backups".

**Comment by morosanuae** [comment]
I have Windows 10 v1909 x64. I will try with a fresh version of Firefox portable with only this addon installed and come back with feedback.

**Comment by morosanuae** [comment]
What I've tried so far:
- Firefox portable v71.0 x64 (PortableApps)  -> not working
- Firefox portable v69.0.3 (PortableApps) -> not working
- Firefox portable v70.0.1 x86 (LiberKey) -> not working
- Firefox standard v72 x64 (non-portable) -> not working
All fresh installations without other addons. None of them seem to work. Can be a Windows problem?

**Comment by morosanuae** [comment]
I've found the problem! Maybe it's related to #32. 
I always use this path: `Downloads > TiddlyWiki > My-Wiki > my-wiki.html` This structure is very useful for me because I have a lot of files with different roles (ex. testing). If a put the file "my-wiki.html" into the root of "Downloads" folder it's working fine.
Can you find a solution that will allow me to use a directory structure like the one I'm using now?

Thanks!

**Comment by morosanuae** [comment]
It also works with `Downloads > TiddlyWiki > my-wiki.html`

**Comment by morosanuae** [comment]
So it looks like the problem is nesting the file too deep.

**Comment by pmario** [comment]
I will check this

**Comment by pmario** [comment]
Hi, What ever I do,  it works for me. ... Can you record a video?

**Comment by morosanuae** [comment]
I really don't know what's happening. I have made a second copy of the entire folder and it's working OK. The old (original) one is not working, the download fail every time. Even if I change the names of files and folders. Isn't that strange?

So I manage to resolve the problem, should I close this issue?

Thanks a lot!

**Comment by pmario** [comment]
It would be nice, if you could have a closer look. ... May be there is a timing issue somewhere. I'll have to have a closer look at the data-flow again.
