### ISSUE TITLE
NoScript prevents editing tiddler content

### ISSUE THREAD

**Issue by pmario** [pmario/file-backups#36]
Have fun!
mario
### PS: If you use it: [Support it!](https://www.paypal.me/PMarioJo)

**Comment by pinysuse** [comment]
Just in case someone else uses that combination of FF Add-ons and to avoid a few hours of pinning it down cf.
[NoScript 11.0.46 breaks TiddlyWiki5 File Backups V0.4.0 on FF 81.0](https://github.com/hackademix/noscript/issues/156)

**Comment by pmario** [comment]
@pinysuse Thx for the info. So you say that NoScript 11.0.45 did work with File Backups? ... If yes, this will give us a clear hint, where to find the problem. Since we only would need to see, what changed between those 2 noscript verisons.

**Comment by pmario** [comment]
The problem is, that I have no idea, what NoScript does and what it is used for.

**Comment by pmario** [comment]
I did install the latest NoScript Add On for FF 81 Win10
I did download empty.html
I did open empty.html ... which was completely blocked by noscript .. So I only got a white screen. 

Then I did set noscript setting to trust file:///.../Downloads/empty.html

I did a reload and the saving mechanism works as expected. So imo if you trust the wiki from the file URI it should be fine.

**Comment by pmario** [comment]
Which OS, which Browser version do you use?

**Comment by pinysuse** [comment]
> Which OS, which Browser version do you use?

   OS:     Linux 4.12.14-lp151.28.67-default x86_64
   System: openSUSE Leap 15.1
   Qt:     5.9.7
   KDE:    5.55.0
   Plasma: 5.12.8
   FF: 81.0 (64-bit)

**Comment by pinysuse** [comment]
> (...)
> Then I did set noscript setting to trust file:///.../Downloads/empty.html
> 
> I did a reload and the saving mechanism works as expected. So imo if you trust the wiki from the file URI it should be fine.

I am not aware that I could trust a specific local file. I think I can generally trust the local `file:` protocol which should cover the wiki. At least up to recently it did.

**Comment by pinysuse** [comment]
Did you enter some text in a new tiddler body and was that text still there after saving?
Here new tiddlers are saved but always w/ empty body!

**Comment by pmario** [comment]
You are right. I doesn't allow to modify the html content. Tiddlywiki uses the html file as its data store. It seems NoScript "freezes" this store. So it doesn't block anything from file-backups. .. It blocks TW core itself.

**Comment by pmario** [comment]
I think I found the problem. See comments at your issue in the noScript repo. .. It has nothing to do with the file-backups plugin. I'm following the noscrip issue and will close this one.

**Comment by pinysuse** [comment]
Thanks for digging into this issue!
