### ISSUE TITLE
Dialog Box when saving outside Downloads folder unclear

### ISSUE THREAD

**Issue by furicle** [pmario/file-backups#6]
I find this dialog box a bit unclear
![image](https://user-images.githubusercontent.com/45774/32981672-a0b0ba34-cc46-11e7-9fda-18a5114d7561.png)

Perhaps something like 

Firefox cannot save this TiddlyWiki in this location.  
$filepath
Try to save again and choose a location inside (under?) $pathToDownloads

**Comment by tobibeer** [comment]
@pmario: I have my default downloads folder defined to be the Desktop. Would that mean that I can then save all TiddlyWikis there (even though I probably still won't but rather use symlinks to a better place?)?

**Comment by pmario** [comment]
Yes. 

File symlinks don't work. you need to use "folder links" ... windows "junctions" to link to other places. ...
And you still need to open the files from the "browser downloads" folder. Otherwise you'll get a "save" dialog.

**Comment by pmario** [comment]
I did remove this dialog, and just open the system "Save As" dialog, that should be known to users. 

@furicle  ... I'll close this issue for now. ... If you think it's still broken with 0.2.1, feel free to reopen it.

**Comment by tobibeer** [comment]
@pmario: Thanks for clearing that up.

Yes, I meant symlinked folders, indeed. Opening files from the symlinked location wouln't be a problem, I guess, One could even set the whole thing to be hidden (in windows explorer), infering the location from the actual location.
